services:
  web:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../..:/app
      - static_volume:/app/huawei_prototype/staticfiles
    expose:
      - 8000
    env_file:
      - ../../.env
    environment:
      - PYTHONPATH=/app/huawei_prototype
      - DJANGO_SETTINGS_MODULE=huawei_prototype.settings
      - DJANGO_DEBUG=1

  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/huawei_prototype/staticfiles:ro
    depends_on:
      - web

volumes:
  static_volume: