services:
  web:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    volumes:
      # Only mount static files volume, NOT source code
      - static_volume:/app/huawei_prototype/staticfiles
    expose:
      - 8000
    env_file:
      - ../../.env.production
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=huawei_prototype.huawei_prototype.settings
      - DJANGO_DEBUG=0
    restart: always
  
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/huawei_prototype/staticfiles:ro
    depends_on:
      - web
    restart: always

volumes:
  static_volume: