# Generated by Django 5.1.7 on 2025-04-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Incident severity level",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AccidentProbabilityScore",
            fields=[
                (
                    "accident_probability_score_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("area_geometry", models.TextField()),
                ("risk_score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accident_probabilitys",
                        to="dashboard.camera",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AccidentPredictionScore",
        ),
    ]
