# Generated by Django 5.1.7 on 2025-04-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_incident_severity_accidentprobabilityscore_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accidentprobabilityscore",
            old_name="risk_score",
            new_name="accident_probability_score",
        ),
        migrations.RenameField(
            model_name="kpisnapshot",
            old_name="high_risk_count",
            new_name="high_accident_probability_count",
        ),
        migrations.RenameField(
            model_name="kpisnapshot",
            old_name="moderate_risk_count",
            new_name="moderate_accident_probability_count",
        ),
    ]
