# Generated by Django 5.1.7 on 2025-04-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0003_rename_risk_score_accidentprobabilityscore_accident_probability_score_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpisnapshot",
            old_name="high_accident_probability_count",
            new_name="high_severity_count",
        ),
        migrations.RenameField(
            model_name="kpisnapshot",
            old_name="moderate_accident_probability_count",
            new_name="moderate_severity_count",
        ),
    ]
