# Generated by Django 5.1.7 on 2025-04-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0004_rename_high_accident_probability_count_kpisnapshot_high_severity_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="accidentprobabilityscore",
            old_name="accident_probability_score",
            new_name="accident_prob_score",
        ),
        migrations.RenameField(
            model_name="accidentprobabilityscore",
            old_name="accident_probability_score_id",
            new_name="accident_prob_score_id",
        ),
    ]
